name: Track Downloads

on:
  schedule:
    - cron: "0 0 * * *" # Run at 00:00 UTC every day
  workflow_dispatch:

jobs:
  track_downloads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib requests python-dateutil

      - name: Fetch download count
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/workflows/downloads/fetch.py

      - name: Plot download data
        run: python .github/workflows/downloads/plot.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloads-csv
          path: downloads.csv

      - name: Upload PNG artifact
        uses: actions/upload-artifact@v2
        with:
          name: downloads-png
          path: downloads.png
